MODEL_JSON_DATA = {
    "Card": [
        {
            "id": 1,
            "name": "K-패스",
            "max_count": 60,
            "min_count": 15,
            "youth_age": 34,
            "min_cost": 0,
            "location_id": 1,
            "senior_age": 65,
            "adult": 20,
            "youth": 30,
            "low": 53,
            "senior": 20,
        },
        {
            "id": 2,
            "name": "인천I패스",
            "max_count": None,
            "min_count": 15,
            "youth_age": 39,
            "min_cost": 0,
            "location_id": 3,
            "senior_age": 65,
            "adult": 20,
            "youth": 30,
            "low": 53,
            "senior": 30,
        },
        {
            "id": 3,
            "name": "The경기패스",
            "max_count": None,
            "min_count": 15,
            "youth_age": 39,
            "min_cost": 0,
            "location_id": 2,
            "senior_age": 65,
            "adult": 20,
            "youth": 30,
            "low": 53,
            "senior": 20,
        },
        {
            "id": 4,
            "name": "기후동행카드",
            "max_count": None,
            "min_count": 0,
            "youth_age": 34,
            "min_cost": 62000,
            "location_id": 4,
            "senior_age": 65,
            "adult": 0,
            "youth": 7000,
            "low": 0,
            "senior": 0,
        },
    ],
    "Location": [
        {"id": 1, "name": "전체"},
        {"id": 2, "name": "경기"},
        {"id": 3, "name": "인천"},
        {"id": 4, "name": "기타"},
    ],
}
